"""Константы проекта Foodgram."""

MAX_EMAIL_LENGTH = 254
MAX_NAME_LENGTH = 150
MAX_TAG_LENGTH = 32
MAX_INGREDIENT_NAME_LENGTH = 128
MAX_MEASUREMENT_UNIT_LENGTH = 64
MAX_RECIPE_NAME_LENGTH = 256
MAX_SHORT_CODE_LENGTH = 10
MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 32000
MIN_AMOUNT = 1
MAX_AMOUNT = 32000
STR_REPR_MAX_LENGTH = 20
PAGE_SIZE = 6
SHORT_CODE_LENGTH = 8
